
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ktw-push:
    runs-on: ubuntu-latest
    name: ktwktwktw
    steps:
      - uses: actions/checkout@v2
      - run: echo Hellow World !
